"""Generate Leish! launch marketing plan slide decks for the MEDIUM and LOW budget tiers.

Usage: python3 scripts/generate-launch-deck-tiers.py
Outputs: docs/launch-marketing-plan-medium.pptx, docs/launch-marketing-plan-low.pptx
High tier deck is generated by scripts/generate-launch-deck.py.
"""
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN, MSO_ANCHOR
from pptx.enum.shapes import MSO_SHAPE
import os

ROSE = RGBColor(0xE1, 0x1D, 0x48)
PINK = RGBColor(0xDB, 0x27, 0x77)
PURPLE = RGBColor(0x8B, 0x5C, 0xF6)
TEAL = RGBColor(0x0E, 0x94, 0x92)
ORANGE = RGBColor(0xD9, 0x77, 0x06)
GREEN = RGBColor(0x65, 0xA3, 0x0D)
DARK = RGBColor(0x1F, 0x29, 0x37)
DARK2 = RGBColor(0x11, 0x18, 0x27)
GRAY = RGBColor(0x6B, 0x72, 0x80)
LIGHT = RGBColor(0xFD, 0xF2, 0xF8)
LIGHT2 = RGBColor(0xF5, 0xF3, 0xFF)
MUTED = RGBColor(0x9C, 0xA3, 0xAF)
WHITE = RGBColor(0xFF, 0xFF, 0xFF)
BORDER = RGBColor(0xE5, 0xE7, 0xEB)

SERIF = "Georgia"
SANS = "Calibri"
OUT_DIR = os.path.join(os.path.dirname(__file__), "..", "docs")


def build(tier):
    prs = Presentation()
    prs.slide_width = Inches(13.333)
    prs.slide_height = Inches(7.5)
    BLANK = prs.slide_layouts[6]
    SW, SH = prs.slide_width, prs.slide_height
    page = [0]

    def slide(bg=WHITE):
        s = prs.slides.add_slide(BLANK)
        r = s.shapes.add_shape(MSO_SHAPE.RECTANGLE, 0, 0, SW, SH)
        r.fill.solid()
        r.fill.fore_color.rgb = bg
        r.line.fill.background()
        r.shadow.inherit = False
        page[0] += 1
        return s

    def box(s, x, y, w, h, fill=None, line=None, shape=MSO_SHAPE.RECTANGLE, radius=None):
        sp = s.shapes.add_shape(shape, Inches(x), Inches(y), Inches(w), Inches(h))
        if fill is None:
            sp.fill.background()
        else:
            sp.fill.solid()
            sp.fill.fore_color.rgb = fill
        if line is None:
            sp.line.fill.background()
        else:
            sp.line.color.rgb = line
            sp.line.width = Pt(1)
        sp.shadow.inherit = False
        if radius is not None and shape == MSO_SHAPE.ROUNDED_RECTANGLE:
            try:
                sp.adjustments[0] = radius
            except Exception:
                pass
        return sp

    def text(s, x, y, w, h, runs, size=14, color=DARK, bold=False, font=SANS,
             align=PP_ALIGN.LEFT, anchor=MSO_ANCHOR.TOP, line_spacing=1.0):
        tb = s.shapes.add_textbox(Inches(x), Inches(y), Inches(w), Inches(h))
        tf = tb.text_frame
        tf.word_wrap = True
        tf.vertical_anchor = anchor
        tf.margin_left = tf.margin_right = tf.margin_top = tf.margin_bottom = 0
        if isinstance(runs, str):
            runs = [runs]
        for i, para in enumerate(runs):
            p = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
            p.alignment = align
            p.line_spacing = line_spacing
            if isinstance(para, str):
                para = [(para, {})]
            for t, st in para:
                r = p.add_run()
                r.text = t
                r.font.name = st.get("font", font)
                r.font.size = Pt(st.get("size", size))
                r.font.bold = st.get("bold", bold)
                r.font.italic = st.get("italic", False)
                r.font.color.rgb = st.get("color", color)
        return tb

    def footer(s, note):
        text(s, 0.6, 7.14, 10.5, 0.3, note, size=9, color=MUTED)
        text(s, 12.3, 7.14, 0.5, 0.3, str(page[0]), size=9, color=MUTED, align=PP_ALIGN.RIGHT)

    def header(s, kicker, title, accent=ROSE):
        text(s, 0.6, 0.42, 11.5, 0.3, kicker.upper(), size=11, color=accent, bold=True)
        text(s, 0.6, 0.72, 12.1, 0.8, title, size=30, color=DARK, bold=True, font=SERIF)
        box(s, 0.62, 1.52, 1.6, 0.045, fill=accent)

    def chip(s, x, y, w, h, label, color, bg=LIGHT, size=11.5):
        box(s, x, y, w, h, fill=bg, shape=MSO_SHAPE.ROUNDED_RECTANGLE, radius=0.5)
        text(s, x, y + 0.05, w, h - 0.1, label, size=size, color=color, bold=True, align=PP_ALIGN.CENTER)

    C = tier["color"]
    FOOT = f"Leish! Launch Marketing Plan · {tier['name']} · RM {tier['budget']:,} / 90 days · Oct 5, 2026"

    # ---------- 1. TITLE ----------
    s = slide(DARK2)
    box(s, 0, 0, SW, 0.14, fill=ROSE)
    box(s, 0, 7.36, SW, 0.14, fill=C)
    box(s, 11.0, -1.7, 4.3, 4.3, fill=C, shape=MSO_SHAPE.OVAL)
    box(s, -1.5, 5.2, 3.9, 3.9, fill=ROSE, shape=MSO_SHAPE.OVAL)
    text(s, 0.9, 1.5, 9.5, 0.4, "LEISH.MY · LAUNCH MARKETING PLAN · 90 DAYS", size=13, color=ROSE, bold=True)
    text(s, 0.9, 2.0, 11.5, 1.3, [
        [(tier["name"], {"size": 40, "bold": True, "font": SERIF, "color": WHITE})],
        [("Never DM for a Date Again. — official launch ", {"size": 18, "color": MUTED}),
         ("October 5, 2026", {"size": 18, "bold": True, "color": WHITE})],
    ], line_spacing=1.15)
    box(s, 0.95, 3.95, 3.6, 1.15, fill=None, line=C, shape=MSO_SHAPE.ROUNDED_RECTANGLE, radius=0.12)
    text(s, 1.2, 4.12, 3.2, 0.85, [
        [("TOTAL BUDGET", {"size": 11, "color": MUTED, "bold": True})],
        [(f"RM {tier['budget']:,}", {"size": 26, "bold": True, "color": WHITE})],
    ], line_spacing=1.05)
    box(s, 4.75, 3.95, 4.1, 1.15, fill=None, line=PINK, shape=MSO_SHAPE.ROUNDED_RECTANGLE, radius=0.12)
    text(s, 5.0, 4.12, 3.7, 0.85, [
        [("DAY-90 HEADLINE", {"size": 11, "color": MUTED, "bold": True})],
        [(tier["headline"], {"size": 14, "bold": True, "color": WHITE})],
    ], line_spacing=1.05)
    box(s, 9.05, 3.95, 3.6, 1.15, fill=None, line=PURPLE, shape=MSO_SHAPE.ROUNDED_RECTANGLE, radius=0.12)
    text(s, 9.3, 4.12, 3.2, 0.85, [
        [("LAUNCH DATE", {"size": 11, "color": MUTED, "bold": True})],
        [("Oct 5, 2026", {"size": 20, "bold": True, "color": WHITE})],
    ], line_spacing=1.05)
    text(s, 0.9, 5.6, 11.0, 0.9, [
        [(tier["title_note"], {"size": 13, "color": MUTED})],
    ], line_spacing=1.2)

    # ---------- 2. STRATEGY ----------
    s = slide()
    header(s, "Executive summary", "The Play — " + tier["name"])
    cols = tier["strategy"]
    cx = 0.6
    for title, c, head, body in cols:
        box(s, cx, 2.0, 3.9, 4.25, fill=LIGHT if c != PURPLE else LIGHT2, shape=MSO_SHAPE.ROUNDED_RECTANGLE, radius=0.06)
        box(s, cx, 2.0, 3.9, 0.14, fill=c)
        text(s, cx + 0.35, 2.45, 3.2, 0.3, title, size=13, color=c, bold=True)
        text(s, cx + 0.35, 2.85, 3.2, 0.9, head, size=18, bold=True, font=SERIF, color=DARK)
        text(s, cx + 0.35, 3.75, 3.25, 2.4, body, size=12.5, color=GRAY, line_spacing=1.2)
        cx += 4.05
    chip(s, 0.6, 6.55, 12.13, 0.42, tier["strategy_chip"], C)

    # ---------- 3. BUDGET ----------
    s = slide()
    header(s, f"RM {tier['budget']:,} · 90 days", "Budget Breakdown")
    yy = 2.0
    for name, amt, c, pct in tier["budget_items"]:
        text(s, 0.6, yy + 0.03, 5.6, 0.35, name, size=12.5, color=DARK, bold=True)
        text(s, 6.35, yy + 0.03, 1.6, 0.35, f"RM {amt:,}", size=12.5, color=GRAY, bold=True, align=PP_ALIGN.RIGHT)
        box(s, 8.1, yy + 0.09, 3.1, 0.24, fill=RGBColor(0xF1, 0xF2, 0xF6), shape=MSO_SHAPE.ROUNDED_RECTANGLE, radius=0.5)
        box(s, 8.1, yy + 0.09, 3.1 * pct, 0.24, fill=c, shape=MSO_SHAPE.ROUNDED_RECTANGLE, radius=0.5)
        text(s, 11.35, yy + 0.03, 1.4, 0.35, f"{int(round(pct * 100))}%", size=12.5, color=DARK, bold=True, align=PP_ALIGN.RIGHT)
        yy += 0.56
    box(s, 0.6, 6.35, 12.1, 0.02, fill=BORDER)
    text(s, 0.6, 6.5, 12.1, 0.55, [
        [("Payback logic: ", {"size": 12, "bold": True, "color": DARK}),
         (tier["payback"], {"size": 12, "color": GRAY})],
    ], line_spacing=1.15)

    # ---------- 4. KPIs ----------
    s = slide()
    header(s, "North-star metric: completed bookings per week", "Day-90 Targets")
    cx, cy = 0.6, 2.0
    for val, label, c in tier["kpis"]:
        box(s, cx, cy, 3.95, 1.35, fill=LIGHT if c != PURPLE else LIGHT2, shape=MSO_SHAPE.ROUNDED_RECTANGLE, radius=0.08)
        box(s, cx, cy, 0.1, 1.35, fill=c)
        text(s, cx + 0.35, cy + 0.18, 3.4, 0.6, val, size=25, bold=True, font=SERIF, color=c)
        text(s, cx + 0.35, cy + 0.85, 3.4, 0.4, label, size=12, color=GRAY, bold=True)
        cx += 4.08
        if cx > 12.0:
            cx = 0.6
            cy += 1.5
    text(s, 0.6, 5.1, 12.1, 0.35, "PROGRESSION", size=12, color=GRAY, bold=True)
    rows = [("KPI", "Pre-launch", "Day 30", "Day 60", "Day 90")] + tier["kpi_rows"]
    tbl = s.shapes.add_table(len(rows), 5, Inches(0.6), Inches(5.45), Inches(12.13), Inches(1.55)).table
    tbl.columns[0].width = Inches(4.4)
    for i in range(1, 5):
        tbl.columns[i].width = Inches(1.93)
    for ri, row in enumerate(rows):
        for ci, val in enumerate(row):
            cell = tbl.cell(ri, ci)
            cell.margin_left = cell.margin_right = Inches(0.12)
            cell.margin_top = cell.margin_bottom = Inches(0.03)
            cell.vertical_anchor = MSO_ANCHOR.MIDDLE
            cell.fill.solid()
            cell.fill.fore_color.rgb = DARK if ri == 0 else (WHITE if ri % 2 else RGBColor(0xFB, 0xF7, 0xFB))
            p = cell.text_frame.paragraphs[0]
            p.alignment = PP_ALIGN.CENTER if ci else PP_ALIGN.LEFT
            r = p.add_run()
            r.text = val
            r.font.size = Pt(12 if ri == 0 else 11)
            r.font.bold = ri == 0 or ci == 0
            r.font.color.rgb = WHITE if ri == 0 else DARK
            r.font.name = SANS

    # ---------- 5. TIMELINE ----------
    s = slide()
    header(s, "Timeline", "Four phases")
    cx = 0.6
    for title, dates, c, items in tier["phases"]:
        box(s, cx, 2.05, 3.0, 4.35, fill=WHITE, line=BORDER, shape=MSO_SHAPE.ROUNDED_RECTANGLE, radius=0.05)
        box(s, cx, 2.05, 3.0, 0.14, fill=c)
        text(s, cx + 0.25, 2.4, 2.55, 0.55, title, size=12.5, color=c, bold=True)
        text(s, cx + 0.25, 2.95, 2.55, 0.3, dates, size=11.5, color=GRAY, bold=True)
        yy = 3.4
        for it in items:
            box(s, cx + 0.28, yy + 0.07, 0.09, 0.09, fill=c, shape=MSO_SHAPE.OVAL)
            text(s, cx + 0.48, yy, 2.35, 0.95, it, size=11, color=DARK, line_spacing=1.05)
            yy += 0.8
        cx += 3.13

    # ---------- 6. CHANNELS ----------
    s = slide()
    header(s, "Channel mix", "Owned · Paid · Earned")
    cx = 0.6
    for title, c, items in tier["channels"]:
        box(s, cx, 2.0, 3.98, 4.75, fill=WHITE, line=BORDER, shape=MSO_SHAPE.ROUNDED_RECTANGLE, radius=0.05)
        box(s, cx, 2.0, 3.98, 0.14, fill=c)
        text(s, cx + 0.3, 2.35, 3.4, 0.35, title, size=15, color=c, bold=True, font=SERIF)
        yy = 2.85
        for it in items:
            box(s, cx + 0.32, yy + 0.08, 0.09, 0.09, fill=c, shape=MSO_SHAPE.OVAL)
            text(s, cx + 0.52, yy, 3.25, 0.8, it, size=10.5, color=DARK, line_spacing=1.05)
            yy += 0.64
        cx += 4.13

    # ---------- 7. OFFERS ----------
    s = slide()
    header(s, "Lock before Day 0", "Launch Offers & Promotions")
    box(s, 0.6, 2.0, 6.0, 4.3, fill=LIGHT, shape=MSO_SHAPE.ROUNDED_RECTANGLE, radius=0.05)
    box(s, 0.6, 2.0, 6.0, 0.14, fill=ROSE)
    text(s, 0.95, 2.3, 5.3, 0.35, "CLIENT SIDE (DEMAND)", size=14, color=ROSE, bold=True)
    yy = 2.85
    for name, desc in tier["client_offers"]:
        box(s, 0.95, yy, 5.3, 0.95, fill=WHITE, shape=MSO_SHAPE.ROUNDED_RECTANGLE, radius=0.1)
        text(s, 1.2, yy + 0.12, 4.9, 0.35, name, size=13, bold=True, color=ROSE)
        text(s, 1.2, yy + 0.5, 4.9, 0.4, desc, size=11.5, color=GRAY)
        yy += 1.08
    box(s, 6.85, 2.0, 6.0, 4.3, fill=LIGHT2, shape=MSO_SHAPE.ROUNDED_RECTANGLE, radius=0.05)
    box(s, 6.85, 2.0, 6.0, 0.14, fill=PURPLE)
    text(s, 7.2, 2.3, 5.3, 0.35, "ARTIST SIDE (SUPPLY)", size=14, color=PURPLE, bold=True)
    yy = 2.85
    for name, desc in tier["artist_offers"]:
        box(s, 7.2, yy, 5.3, 0.95, fill=WHITE, shape=MSO_SHAPE.ROUNDED_RECTANGLE, radius=0.1)
        text(s, 7.45, yy + 0.12, 4.9, 0.35, name, size=13, bold=True, color=PURPLE)
        text(s, 7.45, yy + 0.5, 4.9, 0.4, desc, size=11.5, color=GRAY)
        yy += 1.08
    text(s, 0.6, 6.45, 12.1, 0.4, tier["offers_note"], size=11.5, color=GRAY, line_spacing=1.15)

    # ---------- 8. RISKS ----------
    s = slide()
    header(s, "Watch weekly", "Risks & Mitigations")
    yy = 2.0
    for title, body in tier["risks"]:
        box(s, 0.6, yy, 3.6, 0.95, fill=DARK, shape=MSO_SHAPE.ROUNDED_RECTANGLE, radius=0.09)
        text(s, 0.85, yy + 0.13, 3.15, 0.75, title, size=12, color=WHITE, bold=True, line_spacing=1.05)
        box(s, 4.45, yy, 8.25, 0.95, fill=RGBColor(0xFA, 0xF9, 0xFC), line=BORDER, shape=MSO_SHAPE.ROUNDED_RECTANGLE, radius=0.09)
        text(s, 4.7, yy + 0.12, 7.8, 0.75, body, size=11.5, color=GRAY, line_spacing=1.1)
        yy += 1.08
    text(s, 0.6, 6.55, 12.1, 0.4, [
        [("Guardrails: ", {"size": 12, "bold": True, "color": DARK}),
         (tier["guardrails"], {"size": 12, "color": GRAY})],
    ], line_spacing=1.15)

    # ---------- 9. CHECKLIST + UPGRADE ----------
    s = slide()
    header(s, "Owner checklist + upgrade path", "Execute · Measure · Decide")
    text(s, 0.6, 1.85, 5.8, 0.35, "30-DAY CHECKLIST", size=13, color=C, bold=True)
    yy = 2.3
    for date, task in tier["checklist"][:6]:
        box(s, 0.6, yy, 1.35, 0.5, fill=C, shape=MSO_SHAPE.ROUNDED_RECTANGLE, radius=0.25)
        text(s, 0.6, yy + 0.08, 1.35, 0.36, date, size=11, color=WHITE, bold=True, align=PP_ALIGN.CENTER)
        text(s, 2.1, yy + 0.06, 4.2, 0.5, task, size=11.5, color=DARK, bold=True)
        yy += 0.57
    text(s, 6.7, 1.85, 5.8, 0.35, "UPGRADE / DOWNGRADE", size=13, color=PURPLE, bold=True)
    yy = 2.3
    for label, desc in tier["upgrade"]:
        box(s, 6.7, yy, 1.5, 0.5, fill=PURPLE if "pgrade" in label else GRAY, shape=MSO_SHAPE.ROUNDED_RECTANGLE, radius=0.25)
        text(s, 6.7, yy + 0.08, 1.5, 0.36, label, size=10.5, color=WHITE, bold=True, align=PP_ALIGN.CENTER)
        text(s, 8.4, yy + 0.05, 4.35, 0.75, desc, size=11, color=DARK, line_spacing=1.05)
        yy += 0.57
    text(s, 6.7, 5.6, 6.0, 0.4, "REMAINING CHECKLIST", size=12, color=GRAY, bold=True)
    yy = 6.0
    for date, task in tier["checklist"][6:]:
        box(s, 6.7, yy, 1.35, 0.42, fill=BORDER, shape=MSO_SHAPE.ROUNDED_RECTANGLE, radius=0.25)
        text(s, 6.7, yy + 0.05, 1.35, 0.34, date, size=10, color=DARK, bold=True, align=PP_ALIGN.CENTER)
        text(s, 8.2, yy + 0.05, 4.6, 0.4, task, size=11, color=DARK)
        yy += 0.46
    box(s, 0.6, 5.85, 5.9, 0.02, fill=BORDER)
    text(s, 0.6, 6.0, 5.9, 1.2, tier["checklist_note"], size=11, color=GRAY, line_spacing=1.15)

    # ---------- 10. CLOSING ----------
    s = slide(DARK2)
    box(s, 0, 0, SW, 0.14, fill=ROSE)
    box(s, 0, 7.36, SW, 0.14, fill=C)
    box(s, 11.0, -1.7, 4.3, 4.3, fill=C, shape=MSO_SHAPE.OVAL)
    box(s, -1.5, 5.2, 3.9, 3.9, fill=ROSE, shape=MSO_SHAPE.OVAL)
    text(s, 0.9, 2.1, 11.5, 1.2, [
        [(tier["closing"], {"size": 42, "bold": True, "font": SERIF, "color": WHITE})],
    ], line_spacing=1.1)
    text(s, 0.9, 3.5, 11.0, 0.5, [
        [("Full plan: ", {"size": 14, "color": MUTED}),
         (tier["doc"], {"size": 14, "bold": True, "color": WHITE}),
         ("   ·   Tiers: ", {"size": 14, "color": MUTED}),
         ("docs/launch-marketing-plan-tiers.md", {"size": 14, "bold": True, "color": WHITE})],
    ])
    text(s, 0.9, 4.15, 11.0, 0.5, [
        [("Next step: ", {"size": 14, "bold": True, "color": ROSE}),
         (tier["next_step"], {"size": 14, "color": MUTED})],
    ])
    text(s, 0.9, 6.3, 11.0, 0.5, [
        [("#BookBeautyAnywhere  ·  #NeverDMForADate  ·  Your Beauty, Perfected.", {"size": 13, "color": MUTED, "italic": True})],
    ])

    prs.core_properties.title = f"Leish! Launch Marketing Plan — {tier['name']}"
    prs.core_properties.author = "Leish! (leish.my)"
    prs.core_properties.subject = "90-day go-to-market plan — Oct 5, 2026"
    out = os.path.join(OUT_DIR, tier["out"])
    prs.save(out)
    print(f"Saved: {os.path.abspath(out)} ({os.path.getsize(out):,} bytes, {len(prs.slides._sldIdLst)} slides)")


MEDIUM = {
    "name": "Medium Budget",
    "out": "launch-marketing-plan-medium.pptx",
    "doc": "docs/launch-marketing-plan-medium.md",
    "budget": 40000,
    "color": PINK,
    "headline": "800 clients · 40–45 artists · 15–20 bookings/wk",
    "title_note": "Founder + one part-time marketer. Co-hosted pop-up launch, one micro-KOL wave, Meta + narrow Google. Lean execution, same wedding-season timing.",
    "strategy": [
        ("FOCUS", ROSE, "Lean paid, high intent",
         "Meta RM 12k + Google RM 4k (brand + top-10 keywords). No TikTok ads. Retargeting gets 20% of Meta budget. Every ad set gated at 2x ROAS after 2 weeks."),
        ("STYLE", PINK, "Co-hosted pop-up launch",
         "Partner studios host the venue; Leish! brings booking tech + offers. One wedding expo OR pop-up — decide by lead-cost projection by Sep 15."),
        ("GROWTH LOOP", PURPLE, "Commission-heavy KOLs",
         "6–8 micro creators (10k–50k), 50% flat / 50% booking-code commission (10% of GMV) so they self-motivate. One wave, then referral program from Day 30."),
    ],
    "strategy_chip": "Artist gate before Day 0: 25 bookable artists by Sep 28 · Campaign: Never DM for a date again · Hero categories: Bridal · Hijab · Event",
    "budget_items": [
        ("Meta ads (IG + FB, incl. 20% retargeting)", 12000, ROSE, 0.30),
        ("KOLs — 1 wave, 6–8 micro (10k–50k)", 10000, PINK, 0.25),
        ("Events — 1 co-hosted pop-up OR 1 wedding expo", 6000, PURPLE, 0.15),
        ("Google Search (brand + top-10 keywords)", 4000, ORANGE, 0.10),
        ("Community / campus seeding", 3000, TEAL, 0.075),
        ("Artist acquisition (concierge + referral)", 3000, RGBColor(0x7C, 0x3A, 0xED), 0.075),
        ("PR (direct pitching), design & tools", 2000, GREEN, 0.05),
    ],
    "payback": "CAC ≤ RM 25 → client LTV RM 90–150 (2–3 bookings × RM 300 × 20%). Payback in 1–2 bookings; ROAS gate ≥ 2.5x.",
    "kpis": [
        ("800", "Registered clients", ROSE),
        ("40–45", "Active artists & studios", PINK),
        ("15–20", "Bookings / week", PURPLE),
        ("RM 4.5–6k", "GMV / week", TEAL),
        ("≤ RM 25", "Client CAC (paid)", ORANGE),
        ("≥ 2.5x", "Blended ROAS", RGBColor(0x7C, 0x3A, 0xED)),
    ],
    "kpi_rows": [
        ("Waitlist / clients", "1,000 waitlist", "300", "550", "800"),
        ("Weekly bookings", "—", "6–8", "12", "15–20"),
        ("Commission / wk (20%)", "—", "RM 400", "RM 700", "RM 900–1,200"),
        ("Email list", "1,500", "2,000", "2,500", "3,000"),
        ("Social following", "1,500", "2,500", "3,800", "5,000"),
    ],
    "phases": [
        ("PHASE 0 · PRE-LAUNCH", "Aug 10 – Oct 4", ROSE,
         ["Green-light Aug 10", "Waitlist live Aug 31 (RM30 offer)", "25 anchor artists, concierge", "Teaser content 2x/wk", "KOLs contracted by Sep 21", "Paid test Sep 28"]),
        ("PHASE 1 · LAUNCH WEEK", "Oct 5 – 11", PINK,
         ["Co-hosted pop-up with partner studios", "6–8 micro KOLs post", "Direct-journalist PR pitch", "Meta + Google full ON", "LEISH30 live"]),
        ("PHASE 2 · WEDDING SEASON", "Oct 12 – Dec 31", PURPLE,
         ["Referral program Day 30 (RM15/RM15)", "1 expo booth OR 2 campus pop-ups", "Hijab community push (Nov)", "B2B light — 2–3 pitches", "1 blog/mo SEO"]),
        ("PHASE 3 · REVIEW", "Jan 2027", TEAL,
         ["Score vs Day-90 targets", "≥12 bookings/wk + CAC ≤ RM 25 →", "upgrade to High for CNY", "else fix or downgrade"]),
    ],
    "channels": [
        ("OWNED — FOUNDATION", ROSE, [
            "IG — 3–4 posts + 7 stories + 1 reel / wk",
            "TikTok — 2 reels / wk (repurposed)",
            "FB + bridal/beauty groups — daily",
            "Email (Brevo) — sequence + 1 newsletter/mo",
            "WhatsApp — confirmations + monthly broadcast",
            "SEO — 1 blog/mo on /inspiration + /events",
            "Artist share links — always-on loop",
        ]),
        ("PAID — RM 16K", PINK, [
            "Meta RM 12k — bridal/beauty stacks, KL-Selangor, 20–40",
            "Retargeting = 20% of Meta budget",
            "Google RM 4k — brand + top-10 high-intent keywords",
            "No TikTok ads at this tier",
            "Kill any ad set <2x ROAS after 2 weeks",
        ]),
        ("EARNED + COMMUNITY — RM 19K", PURPLE, [
            "6–8 micro KOLs — 50/50 flat + booking commission",
            "1 co-hosted pop-up OR 1 wedding expo",
            "2 campus pop-ups — Cyberjaya (MMU, Limkokwing)",
            "Direct PR pitch — SAYS, The Star, Malay Mail",
            "Bridal FB group giveaways (RM 500)",
        ]),
    ],
    "client_offers": [
        ("LEISH30", "RM30 off first booking · cap 150 · valid to Day 30"),
        ("Early-bird bonus", "Waitlist members get RM30 + priority access"),
        ("Refer-a-friend", "RM15 credit each · live from Day 30"),
    ],
    "artist_offers": [
        ("Free 3-month Pro listing", "Normally RM 200–500/mo · cap 30 artists"),
        ("0% commission, first 10 bookings", "vs standard 20% · cap 20 artists"),
        ("Artist referral", "RM100 + featured slot on referee's 5th booking"),
    ],
    "offers_note": "⚠ Pre-launch dev task: verify promo-code / credit support in admin before Aug 24 (same as High tier).",
    "risks": [
        ("Small team = content slippage", "Batch content weekly (2 blocks/wk); templates; outsource design per-asset."),
        ("Only 1 KOL wave", "Commission-heavy 50/50 deals; secure 2-month UGC rights in contracts."),
        ("Thin paid budget", "Kill <2x ROAS ad sets after 2 weeks; 20% of Meta budget to retargeting."),
        ("Artist gate not met (25)", "Start concierge Aug 31; fallback: extend free Pro to 6 months."),
        ("Pop-up vs expo choice", "Decide by lead-cost projection; book by Sep 15."),
    ],
    "guardrails": "artists idle 14+ days · no-show <15% · artist response <4 hrs · search→booking ≥2%",
    "checklist": [
        ("Aug 10", "Confirm date + budget"),
        ("Aug 24", "Part-time marketer hired"),
        ("Aug 31", "Waitlist + RM30 offer live"),
        ("Sep 21", "KOL wave contracted (6–8)"),
        ("Sep 28", "25 anchor artists (gate!)"),
        ("Oct 5", "DAY 0 — launch"),
        ("Nov 4", "Referral live · Day-30 review"),
        ("Dec 4", "Day-60 checkpoint → upgrade decision"),
        ("Jan 4", "Day-90 review + Q1'27 plan"),
    ],
    "checklist_note": "GA4/Meta events verified Aug 31 · paid test Sep 28 → full Oct 5 · pop-up/expo locked by Sep 15.",
    "upgrade": [
        ("Upgrade", "Day-60: ≥12 bookings/wk + CAC ≤ RM 25 + artist retention ≥ 80% → scale to High (RM 96k) for CNY season."),
        ("Downgrade", "Day-30: paid CAC > RM 35 → cut Google + half of Meta; shift to community channels."),
    ],
    "closing": "Growth, with discipline.",
    "next_step": "close the 5 tier risks and execute the 12-item checklist; Day-60 checkpoint decides upgrade to High.",
}

LOW = {
    "name": "Low Budget (Bootstrap)",
    "out": "launch-marketing-plan-low.pptx",
    "doc": "docs/launch-marketing-plan-low.md",
    "budget": 10000,
    "color": GREEN,
    "headline": "300 clients · 25 artists · 6–10 bookings/wk",
    "title_note": "Founder-led quiet launch. Community, artist network, referrals and barter — near-zero paid. The goal is proof of unit economics, not scale.",
    "strategy": [
        ("FOCUS", ROSE, "Proof, not scale",
         "Hit consistent weekly bookings at CAC ≤ RM 15 and artist retention ≥ 80% → unlock the Medium plan (RM 40k) for Q1'27 CNY season."),
        ("STYLE", PINK, "Quiet soft launch",
         "No event, no paid splash: waitlist email + organic posts + LEISH30 on Oct 5. Growth via bridal FB groups, campus and co-hosted pop-up."),
        ("GROWTH LOOP", PURPLE, "People over ads",
         "Artist share links (built into the product), referral from Day 1, nano-KOL barter, UGC contests. RM 2.5k retargeting only — no prospecting."),
    ],
    "strategy_chip": "Artist gate: 20 bookable artists by Sep 28 · Offers: LEISH30 cap 100 · Free 6-month Pro for artists (compensates for lower traffic)",
    "budget_items": [
        ("Community & events (co-hosted pop-up, campus, giveaways)", 3000, ROSE, 0.30),
        ("Meta ads — retargeting only (from week 2)", 2500, PINK, 0.25),
        ("Nano KOLs — barter + commission (no big flat fees)", 1500, PURPLE, 0.15),
        ("Artist acquisition (referral fees RM100 × 10)", 1000, ORANGE, 0.10),
        ("Tools & design (Canva Pro, stock, ad tools)", 1000, TEAL, 0.10),
        ("Contingency", 1000, GREEN, 0.10),
    ],
    "payback": "Organic-heavy CAC ≤ RM 15 → LTV RM 90–150 = 6–10x LTV:CAC. Paid is retargeting-only (closing), never prospecting, at this scale.",
    "kpis": [
        ("300", "Registered clients", ROSE),
        ("25", "Active artists & studios", PINK),
        ("6–10", "Bookings / week", PURPLE),
        ("RM 1.8–3k", "GMV / week", TEAL),
        ("≤ RM 15", "Blended CAC (organic-heavy)", ORANGE),
        ("1,200", "Email list", GREEN),
    ],
    "kpi_rows": [
        ("Waitlist / clients", "400 waitlist", "120", "220", "300"),
        ("Weekly bookings", "—", "3–4", "5–7", "6–10"),
        ("Commission / wk (20%)", "—", "RM 180", "RM 300", "RM 360–600"),
        ("Email list", "600", "800", "1,000", "1,200"),
        ("Social following", "600", "1,200", "1,800", "2,500"),
    ],
    "phases": [
        ("PHASE 0 · PRE-LAUNCH", "Aug 10 – Oct 4", ROSE,
         ["Green-light Aug 10", "Waitlist live Sep 7 (RM30 offer)", "20 anchor artists, founder concierge", "Founder content 3x/wk", "No paid before Day 0"]),
        ("PHASE 1 · SOFT LAUNCH", "Oct 5 – 11", PINK,
         ["Quiet launch: waitlist email + organic", "LEISH30 live (cap 100)", "Referral live Day 1 (RM15/RM15)", "Pitch 5 wedding bloggers (free)"]),
        ("PHASE 2 · COMMUNITY GROWTH", "Oct 12 – Dec 31", PURPLE,
         ["Bridal FB groups daily (value posts)", "1 co-hosted pop-up (RM 1.5k)", "Nano-KOL barter + UGC contest", "1 blog/mo long-tail SEO"]),
        ("PHASE 3 · CHECKPOINT", "Jan 2027", TEAL,
         ["≥8 bookings/wk + CAC ≤ RM 15 +", "artist retention ≥ 80% →", "move to Medium (RM 40k)", "for Q1'27 CNY season"]),
    ],
    "channels": [
        ("OWNED FIRST — ~85% OF THE WORK", ROSE, [
            "IG — 3 posts + daily stories + 1 reel / wk",
            "TikTok — 1–2 founder reels / wk",
            "FB + bridal/beauty groups — daily, value-first",
            "Email (Brevo) — sequence + 1 newsletter/mo",
            "Artist share links — the #1 acquisition loop",
            "Founder LinkedIn — weekly build-in-public posts",
            "SEO — 1 long-tail blog/mo",
        ]),
        ("PAID — RM 2.5K", PINK, [
            "Meta retargeting only, from week 2",
            "Audiences: site visitors + waitlist abandoners",
            "Creative: RM30 offer",
            "No Google · No TikTok ads · No prospecting",
            "Pause <1.5x ROAS after 2 weeks",
        ]),
        ("EARNED + COMMUNITY — RM 5.5K", PURPLE, [
            "Nano KOLs (2k–20k) — barter + 10–15% of GMV",
            "Ambassador program — top 10 clients, RM50/mo",
            "1 co-hosted pop-up with partner studio",
            "1 campus pop-up (Cyberjaya)",
            "Bridal FB group giveaways (RM 500)",
            "UGC contest — 5 × RM50 vouchers monthly",
        ]),
    ],
    "client_offers": [
        ("LEISH30", "RM30 off first booking · cap 100 · valid to Day 30"),
        ("Refer-a-friend", "RM15 credit each · live from Day 1"),
        ("UGC contest", "5 × RM50 vouchers · monthly"),
    ],
    "artist_offers": [
        ("Free 6-month Pro listing", "Normally RM 200–500/mo · cap 25 artists"),
        ("0% commission, first 10 bookings", "vs standard 20% · cap 15 artists"),
        ("Artist referral", "RM100 on referee's 5th booking · cap 10"),
    ],
    "offers_note": "⚠ Pre-launch dev task: verify promo-code / credit support in admin before Sep 7 (same as other tiers).",
    "risks": [
        ("Demand too slow → artists churn", "Free 6-month Pro; celebrate every booking publicly; weekly artist check-ins."),
        ("Founder bandwidth", "2 batch content days/wk; templates; hire part-time helper from contingency if bookings justify."),
        ("No PR / low visibility", "FB groups + campus + barter nano-KOLs; accept slower ramp — this tier buys proof, not reach."),
        ("Paid waste at tiny budget", "Retargeting only; pause <1.5x ROAS after 2 weeks."),
        ("Promo abuse", "One code per account; cap 100 redemptions."),
    ],
    "guardrails": "artists idle 14+ days · no-show <15% · artist response <4 hrs · paid cost per booking < RM 40",
    "checklist": [
        ("Aug 10", "Confirm date + budget"),
        ("Sep 7", "Waitlist + RM30 offer live"),
        ("Sep 21", "5 wedding bloggers pitched"),
        ("Sep 28", "20 anchor artists (gate!)"),
        ("Oct 5", "DAY 0 — soft launch"),
        ("Oct 12", "Retargeting ON (week 2)"),
        ("Nov 10", "Co-hosted pop-up"),
        ("Dec 4", "Day-60 checkpoint"),
        ("Jan 4", "Day-90 review → upgrade decision"),
    ],
    "checklist_note": "GA4/Meta events verified Sep 7 · referral live Oct 5 · founder batches content Mon + Thu.",
    "upgrade": [
        ("Upgrade", "Day-60: ≥8 bookings/wk + CAC ≤ RM 15 + artist retention ≥ 80% → move to Medium (RM 40k) for Q1'27 CNY season."),
        ("Hold", "Day-90 GMV/wk < RM 1,500 → diagnose supply/checkout/demand before spending more."),
    ],
    "closing": "Prove it first.",
    "next_step": "run the 10-item founder checklist; the Day-60 checkpoint decides whether Leish! earns the Medium budget for CNY season.",
}

if __name__ == "__main__":
    os.makedirs(OUT_DIR, exist_ok=True)
    for cfg in (MEDIUM, LOW):
        build(cfg)
    print("Done.")
